Develop
OldSorcer/java-filmorate pull request #19
Opened 2022-07-27 09:00 UTC by OldSorcer

2022-07-28 14:04 UTC, Fleaman777 requested changes
Ребята привет.

Поздравляю вас с завершением такой масштабной работы. Вы большие молодцы.
Мне очень понравилась ваша работа, видно что проделан большой путь, и однозначно, небезрезультатный. 
Есть, моменты которые можно улучшить, но ничего критичного.
Что мог бы отметить отдельно: здоровские запросы, составлены грамотно и оптимально, на достойном уровене. Логика в сервисах, тоже на отлично, вопросов практически не вызывает, так же как и контроллеры.
Так держать 💪🏼

2022-07-29 21:09 UTC, Fleaman777 requested changes
Отличные исправления, молодцы! 
Но есть еще немного моментоа которые можно исправить. 

небольшая рекомендация на будущее, если исправления после ревью неглобальные,  лучше их делать в 1 коммите, так будет проще отслеживать измненения после ревью, + ревьюеру легче проверять :)

2022-07-29 21:09 UTC, Fleaman777 commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/dao/impl/FilmDaoImpl.java
> +                "    GROUP BY cl.user_id))));";
неплохой запрос, 
но недавно узнал, что в запросе должно быть не больше 2х подзапросов, 
попробуйте переделать, если не будет получаться, можете обратиться к наставнику

2022-07-30 14:24 UTC, Andrey211102 commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/dao/impl/FilmDaoImpl.java
> +                "    GROUP BY cl.user_id))));";
Запрос по большому счету очень не очень. Тяжело совмещать учебу с работой - сделал , как проще и быстрее. 
Требований к производительности не было. Рефакторинг - маловероятен. 
Был выбор разбить на 2 запроса  к базе - 1. максимальное количество лайков , 2 - уже искать фильмы и т.д.

2022-07-31 20:48 UTC, Fleaman777 reviewed
Все отлично. 
Могу еще раз повторить, вы крутые ! :) 
Получено огромное количество бесценного опыта, который обязательно пригодится. 
Удачи в дальнейшем обучении и в новой карьере

2022-08-03 18:32 UTC, merged